[[redirects]]
  from = "/old-path"
  to = "/"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/old-path"
  to = "/"
  status = 200
  force = false
  query = [ {path = ":path"}, {email = ":email"} ]